import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import { useRouter } from "next/router";

import Footer from "../components/Footer";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

export default function Home({ posts }) {
  const router = useRouter();
  return (
    <div className={styles.home}>
      <Head> 
        <title>Learn To Code - MOHD AMMAR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div className={styles.info}>
        <div className={styles.welcome}>
          <h2>Welcome To </h2>
          <h1>CodingFame</h1>
        </div>
        <button
          className={styles.exp}
          onClick={() => {
            router.push("/blogs");
          }}
        >
          Explore Blogs
        </button>
      </div>
      <h1 className={styles.latest}>Latest Blogs</h1>
      <div className={styles.recent}>
        {posts.map((elem, i) => {
          return (
            <div
              className={styles.blog}
              key={i}
              onClick={() => {
                router.push(`blog/${elem.frontMatter.slug}/`);
              }}
            >
              <Image
                src={elem.frontMatter.image}
                width={200}
                alt="blog_image"
                height={200}
                loading="lazy"
              />
              <h1>{elem.frontMatter.title}</h1>
              <div>
                {elem.frontMatter.description.substring(0, 200) + "..."}
              </div>
              <div className={styles.date}>
                Published On {elem.frontMatter.date}
              </div>
            </div>
          );
        })}
      </div>
      <div className={styles.explore_more}>
        <button
          className={styles.more}
          onClick={() => {
            router.push("/blogs");
          }}
        >
          Explore More{" "}
        </button>
      </div>
      <Footer />
    </div>
  );
}


export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join("blogs"));

 let posts=[];
for(let i=0;i<6;i++){
    const markdownWithMeta = fs.readFileSync(
      path.join("blogs", files[i]),
      "utf-8"
    );
    const { data: frontMatter } = matter(markdownWithMeta);
    posts[i]={frontMatter};
    };
  return {
    props: {posts,},revalidate:2
  };
};
